/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dinoplugin_views_JniProvider */

#ifndef _Included_dinoplugin_views_JniProvider
#define _Included_dinoplugin_views_JniProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dinoplugin_views_JniProvider
 * Method:    getFunctionsJni
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_dinoplugin_views_JniProvider_getFunctionsJni
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     dinoplugin_views_JniProvider
 * Method:    getAssemblyJni
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_dinoplugin_views_JniProvider_getAssemblyJni
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
